// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9YzWpy_X6QmIapqAznAh6HNhO_TkWX_8',
    appId: '1:333330199929:web:1f1de996f201a718c3eba8',
    messagingSenderId: '333330199929',
    projectId: 'carparking-76712',
    authDomain: 'carparking-76712.firebaseapp.com',
    storageBucket: 'carparking-76712.appspot.com',
    measurementId: 'G-S4P7YGTLZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd1Cgo3b311S8yRc2vEx5d2wqXuWqWjNI',
    appId: '1:333330199929:android:d4e43322f4dcf357c3eba8',
    messagingSenderId: '333330199929',
    projectId: 'carparking-76712',
    storageBucket: 'carparking-76712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyI9hQz0vrfYvTgJ__OVCOOw9q0zfJZvA',
    appId: '1:333330199929:ios:8c6439f8cd0a5906c3eba8',
    messagingSenderId: '333330199929',
    projectId: 'carparking-76712',
    storageBucket: 'carparking-76712.appspot.com',
    iosBundleId: 'com.example.carparking2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyI9hQz0vrfYvTgJ__OVCOOw9q0zfJZvA',
    appId: '1:333330199929:ios:8c6439f8cd0a5906c3eba8',
    messagingSenderId: '333330199929',
    projectId: 'carparking-76712',
    storageBucket: 'carparking-76712.appspot.com',
    iosBundleId: 'com.example.carparking2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9YzWpy_X6QmIapqAznAh6HNhO_TkWX_8',
    appId: '1:333330199929:web:6a1242cd5dc6c12ac3eba8',
    messagingSenderId: '333330199929',
    projectId: 'carparking-76712',
    authDomain: 'carparking-76712.firebaseapp.com',
    storageBucket: 'carparking-76712.appspot.com',
    measurementId: 'G-SX55GB06FD',
  );
}
